// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.28.2
// source: testdata/required_field.proto

package testdata

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Thing struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Foo           *string           `protobuf:"bytes,1,opt,name=foo" json:"foo,omitempty"`
	Bar           *Thing_InnerThing `protobuf:"bytes,2,opt,name=bar" json:"bar,omitempty"`
	OptionalValue *string           `protobuf:"bytes,3,opt,name=optional_value,json=optionalValue" json:"optional_value,omitempty"`
}

func (x *Thing) Reset() {
	*x = Thing{}
	if protoimpl.UnsafeEnabled {
		mi := &file_testdata_required_field_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Thing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Thing) ProtoMessage() {}

func (x *Thing) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_required_field_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Thing.ProtoReflect.Descriptor instead.
func (*Thing) Descriptor() ([]byte, []int) {
	return file_testdata_required_field_proto_rawDescGZIP(), []int{0}
}

func (x *Thing) GetFoo() string {
	if x != nil && x.Foo != nil {
		return *x.Foo
	}
	return ""
}

func (x *Thing) GetBar() *Thing_InnerThing {
	if x != nil {
		return x.Bar
	}
	return nil
}

func (x *Thing) GetOptionalValue() string {
	if x != nil && x.OptionalValue != nil {
		return *x.OptionalValue
	}
	return ""
}

type Thing_InnerThing struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AnotherOptionalValue *string `protobuf:"bytes,1,opt,name=another_optional_value,json=anotherOptionalValue" json:"another_optional_value,omitempty"`
}

func (x *Thing_InnerThing) Reset() {
	*x = Thing_InnerThing{}
	if protoimpl.UnsafeEnabled {
		mi := &file_testdata_required_field_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Thing_InnerThing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Thing_InnerThing) ProtoMessage() {}

func (x *Thing_InnerThing) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_required_field_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Thing_InnerThing.ProtoReflect.Descriptor instead.
func (*Thing_InnerThing) Descriptor() ([]byte, []int) {
	return file_testdata_required_field_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Thing_InnerThing) GetAnotherOptionalValue() string {
	if x != nil && x.AnotherOptionalValue != nil {
		return *x.AnotherOptionalValue
	}
	return ""
}

var file_testdata_required_field_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         1000,
		Name:          "required_field",
		Tag:           "varint,1000,opt,name=required_field",
		Filename:      "testdata/required_field.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FileOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         2000,
		Name:          "use_custom_option_nilable",
		Tag:           "varint,2000,opt,name=use_custom_option_nilable",
		Filename:      "testdata/required_field.proto",
	},
}

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional bool required_field = 1000;
	E_RequiredField = &file_testdata_required_field_proto_extTypes[0]
)

// Extension fields to descriptorpb.FileOptions.
var (
	// optional bool use_custom_option_nilable = 2000;
	E_UseCustomOptionNilable = &file_testdata_required_field_proto_extTypes[1]
)

var File_testdata_required_field_proto protoreflect.FileDescriptor

var file_testdata_required_field_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x74, 0x65, 0x73, 0x74, 0x64, 0x61, 0x74, 0x61, 0x2f, 0x72, 0x65, 0x71, 0x75, 0x69,
	0x72, 0x65, 0x64, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x20, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2f, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0xb3, 0x01, 0x0a, 0x05, 0x54, 0x68, 0x69, 0x6e, 0x67, 0x12, 0x15, 0x0a, 0x03, 0x66,
	0x6f, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x03, 0xc0, 0x3e, 0x01, 0x52, 0x03, 0x66,
	0x6f, 0x6f, 0x12, 0x28, 0x0a, 0x03, 0x62, 0x61, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x11, 0x2e, 0x54, 0x68, 0x69, 0x6e, 0x67, 0x2e, 0x49, 0x6e, 0x6e, 0x65, 0x72, 0x54, 0x68, 0x69,
	0x6e, 0x67, 0x42, 0x03, 0xc0, 0x3e, 0x01, 0x52, 0x03, 0x62, 0x61, 0x72, 0x12, 0x25, 0x0a, 0x0e,
	0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x1a, 0x42, 0x0a, 0x0a, 0x49, 0x6e, 0x6e, 0x65, 0x72, 0x54, 0x68, 0x69, 0x6e,
	0x67, 0x12, 0x34, 0x0a, 0x16, 0x61, 0x6e, 0x6f, 0x74, 0x68, 0x65, 0x72, 0x5f, 0x6f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x14, 0x61, 0x6e, 0x6f, 0x74, 0x68, 0x65, 0x72, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x61, 0x6c, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x45, 0x0a, 0x0e, 0x72, 0x65, 0x71, 0x75, 0x69,
	0x72, 0x65, 0x64, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x1d, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x46, 0x69, 0x65, 0x6c,
	0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0xe8, 0x07, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x0d, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x3a, 0x58,
	0x0a, 0x19, 0x75, 0x73, 0x65, 0x5f, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x5f, 0x6f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x5f, 0x6e, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x1c, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x46, 0x69,
	0x6c, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0xd0, 0x0f, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x16, 0x75, 0x73, 0x65, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x4f, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x4e, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x42, 0x0e, 0x80, 0x7d, 0x01, 0x5a, 0x09, 0x74,
	0x65, 0x73, 0x74, 0x64, 0x61, 0x74, 0x61, 0x2f, 0x62, 0x08, 0x65, 0x64, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x70, 0xe8, 0x07,
}

var (
	file_testdata_required_field_proto_rawDescOnce sync.Once
	file_testdata_required_field_proto_rawDescData = file_testdata_required_field_proto_rawDesc
)

func file_testdata_required_field_proto_rawDescGZIP() []byte {
	file_testdata_required_field_proto_rawDescOnce.Do(func() {
		file_testdata_required_field_proto_rawDescData = protoimpl.X.CompressGZIP(file_testdata_required_field_proto_rawDescData)
	})
	return file_testdata_required_field_proto_rawDescData
}

var file_testdata_required_field_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_testdata_required_field_proto_goTypes = []any{
	(*Thing)(nil),                     // 0: Thing
	(*Thing_InnerThing)(nil),          // 1: Thing.InnerThing
	(*descriptorpb.FieldOptions)(nil), // 2: google.protobuf.FieldOptions
	(*descriptorpb.FileOptions)(nil),  // 3: google.protobuf.FileOptions
}
var file_testdata_required_field_proto_depIdxs = []int32{
	1, // 0: Thing.bar:type_name -> Thing.InnerThing
	2, // 1: required_field:extendee -> google.protobuf.FieldOptions
	3, // 2: use_custom_option_nilable:extendee -> google.protobuf.FileOptions
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	1, // [1:3] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_testdata_required_field_proto_init() }
func file_testdata_required_field_proto_init() {
	if File_testdata_required_field_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_testdata_required_field_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Thing); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_testdata_required_field_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*Thing_InnerThing); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_testdata_required_field_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 2,
			NumServices:   0,
		},
		GoTypes:           file_testdata_required_field_proto_goTypes,
		DependencyIndexes: file_testdata_required_field_proto_depIdxs,
		MessageInfos:      file_testdata_required_field_proto_msgTypes,
		ExtensionInfos:    file_testdata_required_field_proto_extTypes,
	}.Build()
	File_testdata_required_field_proto = out.File
	file_testdata_required_field_proto_rawDesc = nil
	file_testdata_required_field_proto_goTypes = nil
	file_testdata_required_field_proto_depIdxs = nil
}
